#!/bin/sh

PATCH=197
ARTIFACT_LINES=0
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/fakenextversion.sh $PATCH
./updates/noop.sh $ARTIFACT_NAME
