#!/bin/sh

PATCH=2
ARTIFACT_LINES=12945
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /tmo/
tar xf $ARTIFACT_NAME
cp -a 2/b.1 /usr/src/sys/GENERIC/Makefile
cp -a 2/b.2 /usr/src/sys/conf/boot
cp -a 2/b.3 /usr/src/sys/h/uba.h
cp -a 2/b.4 /usr/src/sys/mdec
cp -a 2/b.5 /usr/src/sys/pdp/machdep2.c
cp -a 2/b.6 /usr/src/sys/pdp/mch_start.s
cp -a 2/b.7 /usr/src/sys/pdpstand
cp -a 2/b.8 /usr/src/sys/pdpuba/ra.c
cp -a 2/b.9 /usr/src/sys/pdpuba/rl.c
cp -a 2/b.10 /usr/src/sys/pdpuba/rlreg.h
cp -a 2/b.11 /usr/src/sys/pdpuba/tmscp.c
cp -a 2/b.12 /usr/src/sys/pdpuba/xp.c
cp -a 2/b.13 /usr/src/sys/sys/sys_net.c
cp -a 2/b.14 /usr/src/sys/conf/checksys.c
cp -a 2/b.15 /usr/doc/2.10/setup.2.11/2.t
cp -a 2/b.17 /usr/src/sys/h/mtio.h
cp -a 2/b.18 /usr/src/bin/mt.c
cp -a 2/b.19 /usr/src/etc/restor/restor.c
cp -a 2/b.20 /usr/src/etc/icheck.c
cp -a 2/b.21 /usr/src/etc/newfs.c
cp -a 2/b.22 /usr/src/etc/config/config.c
