#!/bin/sh

PATCH=2
ARTIFACT_LINES=12945
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /tmp/
tar xf $ARTIFACT_NAME
patch < 2/b.1
patch < 2/b.2
patch < 2/b.3
patch < 2/b.4
patch < 2/b.5
patch < 2/b.6
patch < 2/b.7
patch < 2/b.8
patch < 2/b.9
patch < 2/b.10
patch < 2/b.11
patch < 2/b.12
patch < 2/b.13
patch < 2/b.14
patch < 2/b.15
patch < 2/b.17
patch < 2/b.18
patch < 2/b.19
patch < 2/b.20
patch < 2/b.21
patch < 2/b.22
