#!/bin/sh

PATCH=206
ARTIFACT_LINES=708
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/fakenextversion.sh $PATCH
./updates/patch.sh $ARTIFACT_NAME
