#!/bin/sh

PATCH=209
ARTIFACT_LINES=492
ARTIFACT_NAME=$PATCH

./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/fakenextversion.sh $PATCH
./updates/patch.sh $ARTIFACT_NAME
