#!/bin/sh

PATCH=210
ARTIFACT_LINES=135
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/endfakeversion.sh $PATCH
./updates/patch.sh $ARTIFACT_NAME

# 197 notes covers full pack 197-210
./updates/buildinstall.sh /usr/src/usr.lib/libcurses
./updates/buildinstall.sh /usr/src/lib/libc

(cd /usr/src/usr.bin/lint && ./libs)

./updates/buildinstall.sh /usr/src/bin/sh
./updates/buildinstall.sh /usr/src/bin/csh
./updates/buildinstall.sh /usr/src/bin/ls
./updates/buildinstall.sh /usr/src/bin/chflags
./updates/buildinstall.sh /usr/src/bin
./updates/buildinstall.sh /usr/src/etc
./updates/buildinstall.sh /usr/src/etc/getty
./updates/buildinstall.sh /usr/src/ucb/ex
./updates/buildinstall.sh /usr/src/ucb/tset
./updates/buildinstall.sh /usr/src/usr.bin
./updates/buildinstall.sh /usr/src/man/man2
./updates/buildinstall.sh /usr/src/man/man1
./updates/buildinstall.sh /usr/src/man/man4
./updates/buildinstall.sh /usr/src/man/man8

./updates/kernel.sh
