#!/bin/sh

PATCH=214
ARTIFACT_LINES=281
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/run.sh $ARTIFACT_NAME

sh /tmp/rm.sh.$PATCH
patch -p0 < /tmp/patch.$PATCH.1 # update /VERSION
patch -p0 < /tmp/patch.$PATCH.2 # update the uucp.h file

cp /tmp/Makefile.$PATCH /usr/src/usr.bin/uucp/Makefile
./updates/buildinstall.sh /usr/src/usr.bin/uucp
