#!/bin/sh

PATCH=215
ARTIFACT_LINES=178
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
rm -f /usr/src/man/man1/ar.1
rm -f /usr/src/man/man1/ranlib.1
rm -f /usr/src/man/man5/ar.5

./updates/patch.sh $ARTIFACT_NAME
