#!/bin/sh

PATCH=219
ARTIFACT_LINES=3561
ARTIFACT_NAME=$PATCH.shar

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/fakenextversion.sh $PATCH
./updates/run.sh $ARTIFACT_NAME
