#!/bin/sh

PATCH=220
ARTIFACT_LINES=23
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/fakenextversion.sh $PATCH
./updates/run.sh $ARTIFACT_NAME
