#!/bin/sh

PATCH=223
ARTIFACT_LINES=1062
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/endfakeversion.sh $PATCH
./updates/patch.sh $ARTIFACT_NAME
./updates/kernel.sh
./updates/buildinstall.sh /usr/src/lib/libc
./updates/buildinstall.sh /usr/src/etc
#reboot

cd /usr/src/usr.bin/lint
./libs

./updates/buildinstall.sh /usr/src/bin/adb
./updates/buildinstall.sh /usr/src/bin/ld
./updates/buildinstall.sh /usr/src/bin/sysctl
./updates/buildinstall.sh /usr/src/etc
./updates/buildinstall.sh /usr/src/games
./updates/buildinstall.sh /usr/src/local/welcome
./updates/buildinstall.sh /usr/src/new/jove
./updates/buildinstall.sh /usr/src/new/la
./updates/buildinstall.sh /usr/src/ucb
./updates/buildinstall.sh /usr/src/usr.lib/sendmail/src
./updates/buildinstall.sh /usr/src/man/man3
