#!/bin/sh

PATCH=223
ARTIFACT_LINES=1062
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
mv /VERSION /VERSION.old && cat /VERSION.old | sed 's@Current Patch Level: '`echo $PATCH-1|bc`'@Current Patch Level: 218@' > /VERSION
cd / ; patch -p0 < /tmp/$ARTIFACT_NAME ; rm /tmp/$ARTIFACT_NAME

# Rebuild and install kernel
sh ./kernel.sh

cd /usr/src/lib/libc
make
make install
make clean

cd /usr/src/etc
make init
install -s -m 755 init /etc/init
#reboot

cd /usr/src/usr.bin/lint
./libs

cd /usr/src/bin/adb
make
make install
make clean

cd /usr/src/bin/ld
make 
make install
make clean

cd /usr/src/bin/sysctl
make
make install
make clean

cd /usr/src/etc
make rwhod bad144
install -s -m 755 rwhod bad144 /etc/rwhod


cd /usr/src/games/warp
make
make install
make clean

cd /usr/src/games/mille
make
make install
make clean

cd /usr/src/games/snake
make
make install
make clean

cd /usr/src/games
make canfield
install -m 755 -s canfield /usr/games


cd /usr/src/local/welcome
cp -p /usr/local/welcome /usr/local/welcome.old
make welcome
make install
make clean


cd /usr/src/new/jove
make 
make install
make clean

cd /usr/src/new/la
make
make install
make clean

cd /usr/src/ucb
make w
install -m 2755 -g kmem -s w /usr/ucb
cd /usr/ucb
rm uptime
ln w uptime


cd /usr/src/usr.lib/sendmail/src
make
make install 
make clean

cd /usr/src/man/man3
/usr/man/manroff sysctl.3 > /usr/man/cat3/sysctl.0
/usr/man/manroff getloadavg.3 > /usr/man/cat3/getloadavg.0
chmod 444 /usr/man/cat3/sysctl.0 /usr/man/cat3/getloadavg.0
