#!/bin/sh

PATCH=224
ARTIFACT_LINES=539
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/patch.sh $ARTIFACT_NAME
./updates/buildinstall.sh /usr/src/new/ntp
