#!/bin/sh

PATCH=225
ARTIFACT_LINES=273
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/patch.sh $ARTIFACT_NAME

cd /usr/src/usr.lib/sendmail/src
m4 < Makefile.m4 > Makefile
make install
/usr/lib/sendmail -bz
make clean

./updates/buildinstall.sh /usr/src/new/ntp
