#!/bin/sh

PATCH=225
ARTIFACT_LINES=273
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd / ; patch -p0 < /tmp/$ARTIFACT_NAME ; rm /tmp/$ARTIFACT_NAME

cd /usr/src/usr.lib/sendmail/src
m4 < Makefile.m4 > Makefile
make install
/usr/lib/sendmail -bz
make clean

cd /usr/src/new/ntp
make
make install
make clean
