#!/bin/sh

PATCH=228
ARTIFACT_LINES=839
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/endfakeversion.sh $PATCH
mkdir /usr/run; chmod 755 /usr/run; ln -s /usr /var
./updates/patch.sh $ARTIFACT_NAME

./updates/buildinstall.sh /usr/src/lib/libc
./updates/buildinstall.sh /usr/src/bin/sysctl
./updates/buildinstall.sh /usr/src/local/welcome
./updates/buildinstall.sh /usr/src/ucb
./updates/buildinstall.sh /usr/src/etc/dev_mkdb
./updates/buildinstall.sh /usr/src/usr.bin/uname
./updates/buildinstall.sh /usr/src/man/man3
./updates/buildinstall.sh /usr/src/man/man1

/etc/dev_mkdb
