#!/bin/sh

PATCH=228
ARTIFACT_LINES=839
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
mv /VERSION /VERSION.old && cat /VERSION.old | sed 's@Current Patch Level: '`echo $PATCH-1|bc`'@Current Patch Level: 226@' > /VERSION
mkdir /usr/run; chmod 755 /usr/run; ln -s /usr /var

cd / ; patch -p0 < /tmp/$ARTIFACT_NAME ; rm /tmp/$ARTIFACT_NAME

cd /usr/src/lib/libc
make
make install
make clean

cd /usr/src/bin/sysctl
make
make install
make clean

cd /usr/src/local/welcome
make 
make install
make clean

cd /usr/src/ucb
make lastcomm
install -s -m 755 lastcomm /usr/ucb

cd /usr/src/etc/dev_mkdb
make 
make install
make clean

cd /usr/src/usr.bin/uname
make 
make install
make clean

cd /usr/src/man/man3
/usr/man/manroff daemon.3 > daemon.0
/usr/man/manroff devname.3 > devname.0
/usr/man/manroff err.3 > err.0
install -m 444 daemon.0 devname.0 err.0 /usr/man/cat3

cd /usr/src/man/man1
/usr/man/manroff lastcomm.1 > /usr/man/cat1/lastcomm.0

/etc/dev_mkdb
