#!/bin/sh

PATCH=229
ARTIFACT_LINES=113
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/patch.sh $ARTIFACT_NAME
sh ./kernel.sh
