#!/bin/sh

PATCH=230
ARTIFACT_LINES=1119
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/patch.sh $ARTIFACT_NAME

cd /usr/src/usr.lib/sendmail/src
m4 < Makefile.m4 > Makefile
make
#kill sendmail
make install
#/usr/lib/sendmail -bz
make clean
