#!/bin/sh

PATCH=231
ARTIFACT_LINES=1817
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/run.sh $ARTIFACT_NAME
sh ./script.$PATCH
rm /tmp/script.$PATCH /tmp/shar.$PATCH /tmp/patch.$PATCH
