#!/bin/sh

PATCH=233
ARTIFACT_LINES=2161
ARTIFACT_NAME=$PATCH

## Verify artifact
./updates/verify.sh $PATCH $ARTIFACT_LINES || exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
./updates/run.sh $ARTIFACT_NAME

cd /usr/src/lib/libc/gen
make depend

./updates/buildinstall.sh /usr/src/lib/libc
./updates/buildinstall.sh /usr/src/man/man3

cd /usr/src/usr.bin/lint
./libs

./updates/buildinstall.sh /usr/src/etc/fingerd

rm /tmp/$PATCH.patch /tmp/$PATCH.shar /tmp/$PATCH.script

rm /usr/src/sys/h/syslog.h.old
rm -r /usr/src/etc/fingerd.old
rm /usr/src/lib/libc/gen/syslog.c.old
rm /usr/src/lib/libc/stdio/sprintf.c.old
rm /usr/src/lib/libc/stdio/vsprintf.c.old
