#!/bin/sh

PATCH=422
ARTIFACT_LINES=4156
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
sed -i 's@Current Patch Level: 421@Current Patch Level: 419@' /VERSION
umask 022
cd /usr/src/usr.sbin
mv cron cron.RM
rm -r /usr/src/usr.sbin/cron.RM
mkdir -p cron/grot
sh /tmp/421
sh /tmp/$ARTIFACT_NAME
patch -p0 < /tmp/420
cd cron
make
make install
make clean
