#!/bin/sh

PATCH=424
ARTIFACT_LINES=478
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /tmp
sh $ARTIFACT_NAME
patch -p0 < $PATCH.patch
sh $PATCH.shar
cd /usr/src/sbin/gt307
make
make install
make clean
