#!/bin/sh

PATCH=426
ARTIFACT_LINES=1868
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /tmp
sh $ARTIFACT_NAME
sh $PATCH.shar
patch -p0 < $Patch.patch
sed -i 's@Current Patch Level: 425@Current Patch Level: 426@' /VERSION
