#!/bin/sh

PATCH=427
ARTIFACT_LINES=1690
ARTIFACT_NAME=$PATCH.patch

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
sed -i 's@Current Patch Level: 426@Current Patch Level: 425@' /VERSION
cd /tmp
patch -p0 < $ARTIFACT_NAME

cd /usr/src/lib/libc
make clean
make
make install
make clean

cd /usr/src/man/man2
/usr/man/manroff select.2 > /usr/man/cat2/select.0
/usr/man/manroff sigwait.2 > /usr/man/cat2/sigwait.0
chmod 444 /usr/man/cat2/sigwait.0

cd /usr/src/share/lint
make install
cd /usr/share/lint
/lib/cpp -C -Dlint llib-lc | /usr/libexec/lint/lint1 -v > llib-lc.ln
chmod a+r *.ln

# Rebuild and install kernel
sh ./updates/kernel.sh
