#!/bin/sh

PATCH=434
ARTIFACT_LINES=222
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd / ; patch -p0 < /tmp/$ARTIFACT_NAME ; rm /tmp/$ARTIFACT_NAME

cd /usr/src/lib/libkern
make clean
make
make install
make clean

cd /sys/pdpstand
make clean
make
cp boot disklabel toyset /

# Rebuild and install kernel
sh ./updates/kernel.sh
