#!/bin/sh

PATCH=442
ARTIFACT_LINES=1808
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /tmp
sh $ARTIFACT_NAME
rm /tmp/$ARTIFACT_NAME
sh $PATCH.shar
patch -p0 < $PATCH.patch
