#!/bin/sh

PATCH=444
ARTIFACT_LINES=129
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME
rm /tmp/$ARTIFACT_NAME

cd /usr/src/libexec/getty
make install
make clean
cd /usr/src/ucb/ftp
make install
make clean
