#!/bin/sh

PATCH=449
ARTIFACT_LINES=1
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME
rm /tmp/$ARTIFACT_NAME

# Rebuild and install kernel
sh ./updates/kernel.sh
