#!/bin/sh

PATCH=453
ARTIFACT_LINES=280
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME

cd /usr/src/bin/tcsh
make
make install
make clean

cd /usr/src/local/welcome
make
make install
make clean
