#!/bin/sh

PATCH=455
ARTIFACT_LINES=38
ARTIFACT_NAME=$PATCH

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0  < /tmp/$ARTIFACT_NAME
cd usr/src/share/zoneinfo
make
install -c -s -m 755 -o bin -g bin zdump /usr/sbin/zdump
make clean
