#!/bin/sh

PATCH=456
ARTIFACT_LINES=466
ARTIFACT_NAME=$PATCH.patch

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME
cd /usr/src/man/man8
/usr/man/manroff fsck.8 > fsck.0
install -c -o bin -g bin -m 444 fsck.0 /usr/man/cat8
rm -f fsck.0

cd /usr/src/sbin/fsck
make
make install
make clean

# Atention YMMV
cd /sys/PIDP11
make
# optionally save the old kernel and networking
mv /unix /ounix
mv /netnix /onetnix
install -c -o root -g wheel -m 744 unix /unix
install -c -o root -g wheel -m 744 netnix /netnix
make clean

# optional
cd /sys/GENERIC
make
install -c -o root -g wheel -m 744 unix /genunix
make clean

# reboot
