#!/bin/sh

PATCH=456
ARTIFACT_LINES=466
ARTIFACT_NAME=$PATCH.patch

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME
cd /usr/src/man/man8
/usr/man/manroff fsck.8 > fsck.0
install -c -o bin -g bin -m 444 fsck.0 /usr/man/cat8
rm -f fsck.0

cd /usr/src/sbin/fsck
make
make install
make clean

# Rebuild and install kernel
sh ./updates/kernel.sh
