#!/bin/sh

PATCH=458
ARTIFACT_LINES=190
ARTIFACT_NAME=$PATCH.patch

## Verify artifact
wc -l /tmp/$PATCH.artifact | \
    grep -c "\ $ARTIFACT_LINES\ /tmp/" || \
    exit 1

## Rename artifact
mv /tmp/$PATCH.artifact /tmp/$ARTIFACT_NAME

## Fix
cd /
patch -p0 < /tmp/$ARTIFACT_NAME
cd /usr/src/bin/tcsh
make
make install
make clean

# Rebuild and install kernel
sh ./updates/kernel.sh
